services:
  spark_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmdb_movies_spark
    ports:
      - "4040:4040"
    volumes:
      - ./data:/tmdbmovies/app/data
      - ./etl:/tmdbmovies/app/etl
      - ./logs:/tmdbmovies/app/logs
      - ./kpis:/tmdbmovies/app/kpis
      - ./main.py:/tmdbmovies/app/main.py 
      - ./visualisation.py:/tmdbmovies/app/visualisation.py 
    env_file:
      - .env
    networks:
      - streaming_network
    restart: unless-stopped

networks:
  streaming_network:
    driver: bridge
