services:
  spark_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmdb_movies_spark
    ports:
      - "4040:4040"
    volumes:
      - ./data:/tmdbmovies/app/data
      - ./etl:/tmdbmovies/app/etl
      - ./logs:/tmdbmovies/app/logs
    env_file:
      - .env
    networks:
      - streaming_network
    restart: unless-stopped

networks:
  streaming_network:
    driver: bridge
